# .prettierrc.toml

# Adapted from https://github.com/typescript-eslint/typescript-eslint/.prettierrc.json
arrowParens = "always"
bracketSpacing = true
endOfLine = "lf"
bracketSameLine = false
jsxSingleQuote = false
printWidth = 80
proseWrap = "preserve"
quoteProps = "consistent"
semi = true
singleQuote = false
tabWidth = 2
trailingComma = "all"
useTabs = false

# START Solidity files config
# From https://github.com/prettier-solidity/prettier-plugin-solidity#readme
[[overrides]]
files = "*.sol"
[overrides.options]
printWidth = 120
tabWidth = 4
useTabs = false
singleQuote = false
bracketSpacing = false
# END Solidity files config
